/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/_console/index'
import { Route as ConsoleOperationsRouteImport } from './routes/_console/operations'
import { Route as ConsoleSettingsRouteImport } from './routes/_console/settings'
import { Route as ConsoleAppsIndexRouteImport } from './routes/_console/apps/index'
import { Route as ConsoleAppsClientIdRouteImport } from './routes/_console/apps/$clientId'
import { Route as ConsoleUsersIndexRouteImport } from './routes/_console/users/index'
import { Route as ConsoleUsersUserIdRouteImport } from './routes/_console/users/$userId'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleOperationsRoute = ConsoleOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsIndexRoute = ConsoleAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAppsClientIdRoute = ConsoleAppsClientIdRouteImport.update({
  id: '/apps/$clientId',
  path: '/apps/$clientId',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersIndexRoute = ConsoleUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleUsersUserIdRoute = ConsoleUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/operations': typeof ConsoleOperationsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/users/$userId': typeof ConsoleUsersUserIdRoute
  '/apps/': typeof ConsoleAppsIndexRoute
  '/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/operations': typeof ConsoleOperationsRoute
  '/settings': typeof ConsoleSettingsRoute
  '/': typeof ConsoleIndexRoute
  '/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/users/$userId': typeof ConsoleUsersUserIdRoute
  '/apps': typeof ConsoleAppsIndexRoute
  '/users': typeof ConsoleUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/operations': typeof ConsoleOperationsRoute
  '/_console/settings': typeof ConsoleSettingsRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/apps/$clientId': typeof ConsoleAppsClientIdRoute
  '/_console/users/$userId': typeof ConsoleUsersUserIdRoute
  '/_console/apps/': typeof ConsoleAppsIndexRoute
  '/_console/users/': typeof ConsoleUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/operations'
    | '/settings'
    | '/apps/$clientId'
    | '/users/$userId'
    | '/apps/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/operations'
    | '/settings'
    | '/'
    | '/apps/$clientId'
    | '/users/$userId'
    | '/apps'
    | '/users'
  id:
    | '__root__'
    | '/_console'
    | '/login'
    | '/_console/operations'
    | '/_console/settings'
    | '/_console/'
    | '/_console/apps/$clientId'
    | '/_console/users/$userId'
    | '/_console/apps/'
    | '/_console/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/operations': {
      id: '/_console/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof ConsoleOperationsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/settings': {
      id: '/_console/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/apps/': {
      id: '/_console/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof ConsoleAppsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/apps/$clientId': {
      id: '/_console/apps/$clientId'
      path: '/apps/$clientId'
      fullPath: '/apps/$clientId'
      preLoaderRoute: typeof ConsoleAppsClientIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/users/': {
      id: '/_console/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ConsoleUsersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/users/$userId': {
      id: '/_console/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof ConsoleUsersUserIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleOperationsRoute: typeof ConsoleOperationsRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleAppsClientIdRoute: typeof ConsoleAppsClientIdRoute
  ConsoleUsersUserIdRoute: typeof ConsoleUsersUserIdRoute
  ConsoleAppsIndexRoute: typeof ConsoleAppsIndexRoute
  ConsoleUsersIndexRoute: typeof ConsoleUsersIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleOperationsRoute: ConsoleOperationsRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleAppsClientIdRoute: ConsoleAppsClientIdRoute,
  ConsoleUsersUserIdRoute: ConsoleUsersUserIdRoute,
  ConsoleAppsIndexRoute: ConsoleAppsIndexRoute,
  ConsoleUsersIndexRoute: ConsoleUsersIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
